//
//  ContentView.swift
//  basicsLecture
//
//  Created by Jehan Fernando on 2026-09-30.
//

import SwiftUI

//protocol MyProtocol {
//    
//}
//
//class CParent: MyProtocol {
//    
//}
//
//class SParent: MyProtocol {
//    
//}
//
//
//


// An enum defines a fixed set of possible values.
// CaseIterable allows us to access all cases using MuscleGroup.allCases.

enum MuscleGroup: CaseIterable {
    case chest
    case legs
    case back
    case shoulders
    case arms
}

// An extension adds functionality to an existing type
// without modifying its original definition.
extension MuscleGroup {
    // Computed property
    // A computed property calculates its value when accessed.
        // It does not store a separate value in memory.
    var displayName: String {
        switch self {
        case .chest:
            return "chest group"
        case .legs:
            return "legs group"
        case .back:
            return "back group"
        case .shoulders:
            return "shoulders group"
        case .arms:
            return "arms group"
        }
    }
    
}

struct Workout {
    // Stored property
    let name: String
    let muscleGroup: MuscleGroup
    let duration: Int
    
    // lazy property
    // A lazy stored property is initialized only when it is first accessed.
        // It must be declared with 'var' because its value is assigned later.
    
//    lazy var iit: String = {
//        // some complex logic
//        return "iit"
//    }()
    
}

// Accepts a Workout object and returns true if its duration is 50 minutes or more.
func isLongWorkout(workout: Workout) -> Bool {
    workout.duration >= 50
}

struct ContentView: View {
    
    // An array containing Workout instances.
        // Each instance is created using the memberwise initializer generated by Swift.
    let workouts = [
        Workout(name: "Bench Press", muscleGroup: .chest, duration: 45),
        Workout(name: "Incline Bench Press", muscleGroup: .chest, duration: 45),
        Workout(name: "Squats", muscleGroup: .legs, duration: 60),
        Workout(name: "PullUps", muscleGroup: .back, duration: 30)
    ]
    
    
    // @ViewBuilder allows us to combine multiple views
    // into a single view-building property.
    @ViewBuilder
    var greeting1: some View {

        //            ForEach(MuscleGroup.allCases, id: \.self) { group in
        //
        //                Text("\(group.displayName)")
        //
        //            }
        //
        //            Divider()

        Section {

            // ForEach repeats the view for every workout in the array. Identifiable values are not required here because we provide an ID using the workout name.
            ForEach(workouts, id: \.name) { workout in

                VStack(alignment: .leading) {

                    Text(workout.name)

                    // String interpolation converts the values into displayable text.

                    Text("\(workout.muscleGroup)")

                    Text("\(workout.duration)")

                }

            }

        }

    }

    @ViewBuilder
    var greeting2: some View {

        Section {

            // let filteredItems = workouts.filter(isLongWorkout)

            // let filteredItems = workouts.filter { workout in
            //    workout.duration >= 50
            //   }

            let filteredItems = workouts.filter {

                $0.duration >= 50

            }

            // Display only the filtered workouts.
            ForEach(filteredItems, id: \.name) { workout in

                VStack(alignment: .leading) {

                    Text(workout.name)

                    Text("\(workout.muscleGroup)")

                    Text("\(workout.duration)")

                }

            }

        }

    }

    var body: some View {

        List {

            greeting1

            greeting2

        }

    }

}
        
#Preview {
    ContentView()
}

        
    
//
//let intArray = [1,2,3,4,5]
//let stringArr ["a","b","c","d","e"]
//
//
////func returnFirstValue<T>(array: [T]) -> T {
////    return array[0]
////}
//


/* <T> makes this a generic function.
 T can represent different types, such as Int or String.
 The function returns the first element of the supplied array.
 */


//
//func returnFirstValue<T>(externalParamName x: [T]) -> T {
//    return x[0]
//}
//
//returnFirstValue(externalParamName: intArray)

//returnFirstValue(array: intArray)
//returnFirstValue(array: stringArr)

//func returnFirstIntValue(array: [Int]) -> Int {
//    return array[0]
//}
//
//func returnFirstStringValue(array: [String]) -> String {
//    return array[0]
//}





